<?php

namespace GetOlympus\Zeus\Utils;

use Behat\Transliterator\Transliterator;

/**
 * Helpers controller
 *
 * @package    OlympusZeusCore
 * @subpackage Utils
 * @author     Achraf Chouk <achrafchouk@gmail.com>
 * @since      0.0.46
 *
 */

class Helpers
{
    /**
     * @var Singleton
     */
    private static $instance;

    /**
     * Get singleton.
     *
     * @return self
     */
    public static function getInstance()
    {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Copy a file contents from this internal assets folder to the public dist Olympus assets folder.
     *
     * @param  string  $sourcePath
     * @param  string  $targetPath
     * @param  string  $filename
     * @param  bool    $symlink
     */
    public static function copyFile($sourcePath, $targetPath, $filename, $symlink = false) : void
    {
        // Check paths
        if ($sourcePath === $targetPath) {
            return;
        }

        $targetFile = rtrim($targetPath, S).S.$filename;

        // Check if file exists and create it
        if (file_exists($targetFile)) {
            return;
        }

        // Build new contents
        $sourceFile = rtrim($sourcePath, S).S.$filename;

        // Check the old file to copy its contents
        if (file_exists($sourceFile)) {
            $copy = $symlink ? symlink($sourceFile, $targetFile) : copy(realpath($sourceFile), $targetFile);
        } else {
            self::filePutContents(
                $targetFile,
                '',
                'This file has been auto-generated by the Zeus package without any content'
            );
        }
    }

    /**
     * Helper function to create a file in a target path with its contents.
     *
     * @param  string  $filepath
     * @param  string  $contents
     * @param  string  $message
     * @param  bool    $usedate
     */
    public static function filePutContents($filepath, $contents, $message, $usedate = true) : void
    {
        $suffix = '';

        // Check date
        if ($usedate) {
            $suffix = ' on '.date('l jS \of F Y h:i:s A');
        }

        // Update contents
        $contents = !empty($contents) ? $contents."\n" : $contents;

        // Copy file contents
        file_put_contents($filepath, "/**\n * ".$message.$suffix.".\n */\n\n".$contents);
    }

    /**
     * Camelize string.
     *
     * @param  string  $text
     * @param  string  $separator
     *
     * @return string
     */
    public static function toCamelCaseFormat($text, $separator = '-') : string
    {
        $slugified = self::urlize($text, $separator);
        $camel = strtolower($slugified);
        $camel = ucwords($camel, $separator);

        return str_replace($separator, '', $camel);
    }

    /**
     * Functionize string.
     *
     * @param  string  $text
     * @param  string  $separator
     *
     * @return string
     */
    public static function toFunctionFormat($text, $separator = '-') : string
    {
        $camelized = self::toCamelCaseFormat($text, $separator);

        return lcfirst($camelized);
    }

    /**
     * Slugify string.
     *
     * @param  string  $text
     * @param  string  $separator
     *
     * @return string
     */
    public static function urlize($text, $separator = '-') : string
    {
        return Transliterator::urlize($text, $separator);
    }
}
